version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok
    username: developer
    password: dummy-since-this-is-a-public-repo

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    registries:
      - "interlok"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "java"
      - "develop"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella

  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    registries:
      - "interlok"
    schedule:
      interval: "weekly"
    target-branch: "develop-v4"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "java"
      - "develop-v4"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "develop"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    target-branch: "develop-v4"
    allow:
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "develop-v4"
    reviewers:
      - aaron-mcgrath-adp
      - sebastien-belin-adp
      - higgyfella
